--- git_perf/src/git/git_interop.rs
+++ delete match arm GitError::RefConcurrentModification{..} | GitError::RefFailedToLock{..} in pull_internal
@@ -762,17 +762,17 @@
 }
 
 fn pull_internal(work_dir: Option<&Path>) -> Result<(), GitError> {
     fetch(work_dir).or_else(|err| match err {
         // A concurrent modification comes from a concurrent fetch.
         // Don't fail for that.
         // TODO(kaihowl) must potentially be moved into the retry logic from the push backoff as it
         // only is there safe to assume that we successfully pulled.
-        GitError::RefConcurrentModification { .. } | GitError::RefFailedToLock { .. } => Ok(()),
+         /* ~ changed by cargo-mutants ~ */
         _ => Err(err),
     })?;
 
     Ok(())
 }
 
 pub fn push(work_dir: Option<&Path>) -> Result<()> {
     let op = || {
